import './global.css';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Welcome to org',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang="en">
    <body>{children}</body>
  </html>
);

export default RootLayout;
